language: java
jdk: openjdk11
sudo: required
dist: trusty

services:
  - docker

install: true

jobs:
  include:
    - stage: commit stage
      script:
        - make clean && make build
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker tag gradle-docker-pipeline:latest $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER
    - stage: acceptance testing
      script:
        - docker pull $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER gradle-docker-pipeline:latest
        - make test
    - stage: promote image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker pull $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER
        - docker tag $DOCKER_USERNAME/gradle-docker-pipeline:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/gradle-docker-pipeline:latest
        - docker push $DOCKER_USERNAME/gradle-docker-pipeline:latest

notifications:
  email:
    on_success: change
    on_failure: always
